name: Frontend CI with Admin Panel

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  frontend-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # It's generally more stable to use LTS versions like 16

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci  # Use `npm ci` for consistent and clean installations

      - name: Run linter (ESLint)
        run: npm run lint

      - name: Build frontend (Vite)
        run: npm run build

  admin-panel:
    needs: frontend-checks
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Notify admin or approve pull request
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}  # PAT for auto-merge
          repository: ${{ github.repository }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge

      - name: Admin Panel Actions
        run: |
          echo "Performing admin tasks for pull request: ${{ github.event.pull_request.number }}"
          # Here, you could trigger any admin-related actions, e.g., sending notifications, creating issue labels, etc.
        
      - name: Label PR with "Admin Approved"
        uses: github/labeler-action@v1
        with:
          labels: 'Admin Approved'
        if: github.event_name == 'pull_request'
